### ISSUE TITLE
Player/Map Scaling

### ISSUE THREAD

**Issue by Demodude123** [Demodude123/HeroesofEternalWarfare#2]
Player is too big for the map/the map is too small for the player. Need to figure out the best way to approach this situation.

**Comment by Demodude123** [comment]
Still need to scale stuff

**Comment by voper45** [comment]
no

**Comment by Demodude123** [comment]
Yes!

**Comment by Demodude123** [comment]
Is it fixed yet?

**Comment by Demodude123** [comment]
Seems to be fixed by Voper, will reopen again if it becomes an issue.
